# Generated by Django 3.1.3 on 2023-12-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posgresdatamodels',
            old_name='magnet',
            new_name='id_torrent',
        ),
    ]
