# Generated by Django 3.1.3 on 2023-12-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bls', '0002_auto_20231217_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='TpbDataModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.TextField()),
                ('end_page', models.TextField()),
                ('url_parse', models.TextField()),
                ('start_url', models.TextField()),
                ('timer', models.TextField()),
            ],
            options={
                'db_table': 'settings_tpb',
            },
        ),
    ]
