# Generated by Django 3.1.3 on 2023-12-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bls', '0004_tpbdatamodels_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpbdatamodels',
            name='auto_scraper',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
