# Generated by Django 3.1.3 on 2024-01-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bls', '0005_tpbdatamodels_auto_scraper'),
    ]

    operations = [
        migrations.CreateModel(
            name='TpbStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'tpb_status',
            },
        ),
    ]
