# Generated by Django 3.1.3 on 2024-01-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bls', '0006_tpbstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='posgresdatamodels',
            name='audio',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posgresdatamodels',
            name='video',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
