# Generated by Django 3.1.3 on 2024-01-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bls', '0007_auto_20240121_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posgresdatamodels',
            name='audio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posgresdatamodels',
            name='video',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
