# Generated by Django 3.1.3 on 2024-01-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bls', '0008_auto_20240126_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.TextField()),
                ('word', models.TextField()),
            ],
            options={
                'db_table': 'adult_filter',
            },
        ),
    ]
