# Generated by Django 3.1.3 on 2024-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bls', '0009_adultfiltermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EztvDataModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.TextField()),
                ('offset', models.TextField()),
                ('url_parse', models.TextField()),
                ('allowed_domains', models.TextField()),
                ('timer', models.TextField()),
                ('name', models.TextField()),
                ('auto_scraper', models.TextField()),
            ],
            options={
                'db_table': 'settings_eztv',
            },
        ),
        migrations.CreateModel(
            name='EztvStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'eztv_status',
            },
        ),
    ]
