# Generated by Django 3.1.3 on 2024-02-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bls', '0010_eztvdatamodels_eztvstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='YtsDataModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.TextField()),
                ('offset', models.TextField()),
                ('url_parse', models.TextField()),
                ('allowed_domains', models.TextField()),
                ('timer', models.TextField()),
                ('name', models.TextField()),
                ('auto_scraper', models.TextField()),
            ],
            options={
                'db_table': 'settings_yts',
            },
        ),
        migrations.CreateModel(
            name='YtsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'yts_status',
            },
        ),
    ]
